name: 'SFTP Upload'
color: 'green'
icon: 'upload'
description: 'Upload files to server via SFTP'
inputs:
  host:
    required: true
  port:
    required: false
    default: 22
  username:
    required: false
    default: 'root'
  password:
    required: true
  localDir:
    required: true
  remoteDir:
    required: true

runs:
  using: 'node12'
  main: 'sftp.js'
